# Generated by Django 3.2 on 2022-08-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='personal',
            field=models.BooleanField(default=True),
        ),
    ]
