# Generated by Django 3.2 on 2022-08-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220822_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default/default.png', upload_to='projects/'),
        ),
    ]
